#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
parse_io_to_tcl.py

从 Innovus .io 文件中提取 top/left/right/bottom 的 PAD 名称，
同时生成两个 Tcl 文件：
  1) gen_pad.tcl      → myppad60 命令
  2) delete_pad.tcl   → deleteInst 命令
"""

import re

input_file = "sisyphus_top.saveloc.io"
gen_file = "gen_pad.tcl"
del_file = "delete_pad.tcl"

# 只处理这四个方向
valid_dirs = ["top", "bottom", "left", "right"]

with open(input_file, "r", encoding="utf-8") as f:
    data = f.read()

gen_results = []
del_results = []

# 正则匹配四个方向的块
pattern = re.compile(r"\((top|bottom|left|right)\s+(.*?)\n\s*\)", re.S)
sections = pattern.findall(data)

for direction, content in sections:
    names = re.findall(r'name="([^"]+)"', content)
    for n in names:
        # 跳过电源、地、corner，如果需要保留请注释掉下面两行
        # if re.search(r"VDD|VSS|CORNER", n, re.IGNORECASE):
        #     continue

        # 无论是否带 _pad，都再加一次 _pad
        pad_name = f"{n}_pad"

        gen_results.append(f"myppad60 {n} {pad_name} {direction} out")
        del_results.append(f"deleteInst {pad_name}")

# 输出 gen_pad.tcl
with open(gen_file, "w", encoding="utf-8") as f:
    f.write("# Auto-generated Tcl script from .io file\n")
    f.write("# Generated by parse_io_to_tcl_allinone.py\n\n")
    for r in gen_results:
        f.write(r + "\n")

# 输出 delete_pad.tcl
with open(del_file, "w", encoding="utf-8") as f:
    f.write("# Auto-generated delete Tcl script from .io file\n")
    f.write("# Generated by parse_io_to_tcl_allinone.py\n\n")
    for r in del_results:
        f.write(r + "\n")

print(f"Generated {len(gen_results)} lines:")
print(f"  → {gen_file}")
print(f"  → {del_file}")
